// Mocks generated by Mockito 5.4.4 from annotations
// in jarvis/test/MOCK/email_sorting_runner_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:jarvis/backend/email_fetch_service.dart' as _i3;
import 'package:jarvis/backend/email_gmail_class.dart' as _i5;
import 'package:jarvis/backend/email_sort_controller.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EmailFetchingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailFetchingService extends _i1.Mock
    implements _i3.EmailFetchingService {
  MockEmailFetchingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  _i4.Future<List<_i5.EmailMessage>> fetchEmails(
    String? accessToken,
    int? count,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchEmails,
          [
            accessToken,
            count,
          ],
        ),
        returnValue:
            _i4.Future<List<_i5.EmailMessage>>.value(<_i5.EmailMessage>[]),
      ) as _i4.Future<List<_i5.EmailMessage>>);
}

/// A class which mocks [EmailSortController].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailSortController extends _i1.Mock
    implements _i6.EmailSortController {
  MockEmailSortController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<Map<String, dynamic>>> categorizeEmailsList(
          List<Map<String, String>>? emails) =>
      (super.noSuchMethod(
        Invocation.method(
          #categorizeEmailsList,
          [emails],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);
}
